joint_position_controller:
  ros__parameters:
    joint_names: ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6", "joint7"]
    target_joint_positions: [0.0, -0.785, 0.0, -2.35, 0.0, 1.571, 0.785]